
version: '3.9'

services:
  backend:
    build: .
    container_name: backend
    command: gunicorn core.wsgi --bind 0.0.0.0:8000 --timeout 300
    volumes:
      - ./core:/app
      - media_volume:/app/media

    environment:
      - ALLOWED_HOSTS=haniadibazad.ir,www.haniadibazad.ir
      - SECRET_KEY=test
      - DEBUG=True
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hadib_user1
      - POSTGRES_PASSWORD=hadib_pass1
      - POSTGRES_DB=hadib_db

  nginx:
    image: nginx
    container_name: nginx
    restart: always
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./core/static:/home/app/static
      - media_volume:/home/app/media
    depends_on:
      - backend
    ports:
      - "9000:80"
volumes:
  postgres_data:
  media_volume:  
