# Generated by Django 5.1.3 on 2025-01-30 09:39

import OTP.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OTPRequest',
            fields=[
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('channel', models.CharField(choices=[('phone', 'Phone'), ('email', 'Email')], default='email', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('receiver', models.CharField(max_length=50)),
                ('password', models.CharField(default=OTP.models.generate_otp, max_length=6)),
            ],
        ),
    ]
